[package]
name = "Omsi2Komsi"
version = "0.1.0"
edition = "2021"
rust-version = "1.78"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "*"
winapi = { version = "0.3.9", features = ["consoleapi", "minwindef"] }
user32-sys = "0.2.0"
serialport = "4.3.0"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
reqwest = { version = "0.11", features = ["json","blocking"] }


[dependencies.windows]
version = "0.*"
features = [
    "Win32_Foundation",
    "Win32_System_SystemServices",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading"
]

